Rails and React/Full Stack Application (CI1010)/Rails Backend/config/routes.rb
Rails.application.routes.draw do
  resources :majors
  resources :courses
  resources :students
  resources :enrolments

  post "/login", to: "sessions#login"
  post "/signup", to: "sessions#signup"

  resources :todos
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Rails and React/Full Stack Application (CI1010)/Rails Backend/app/models/enrolment.rb
class Enrolment < ApplicationRecord
  belongs_to :student
end

Rails and React/Full Stack Application (CI1010)/Rails Backend/app/controllers/enrolments_controller.rb
class EnrolmentsController < ApplicationController
  before_action :set_enrolment, only: %i[ show edit update destroy ]

  # GET /enrolments or /enrolments.json
  def index
    @enrolments = Enrolment.all
  end

  # GET /enrolments/1 or /enrolments/1.json
  def show
  end

  # GET /enrolments/new
  def new
    @enrolment = Enrolment.new
  end

  # GET /enrolments/1/edit
  def edit
  end

  # POST /enrolments or /enrolments.json
  def create
    @enrolment = Enrolment.new(enrolment_params)

    respond_to do |format|
      if @enrolment.save
        format.html { redirect_to enrolment_url(@enrolment), notice: "Enrolment was successfully created." }
        format.json { render :show, status: :created, location: @enrolment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrolment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrolments/1 or /enrolments/1.json
  def update
    respond_to do |format|
      if @enrolment.update(enrolment_params)
        format.html { redirect_to enrolment_url(@enrolment), notice: "Enrolment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrolment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrolment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrolments/1 or /enrolments/1.json
  def destroy
    @enrolment.destroy

    respond_to do |format|
      format.html { redirect_to enrolments_url, notice: "Enrolment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrolment
      @enrolment = Enrolment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrolment_params
      params.require(:enrolment).permit(:code, :student_id)
    end
end

Rails and React/Full Stack Application (CI1010)/Rails Backend/app/helpers/enrolments_helper.rb
module EnrolmentsHelper
end

Rails and React/Full Stack Application (CI1010)/Rails Backend/app/views/enrolments/_enrolment.html.erb
<div id="<%= dom_id enrolment %>">
  <p>
    <strong>Code:</strong>
    <%= enrolment.code %>
  </p>

  <p>
    <strong>Student:</strong>
    <%= enrolment.student_id %>
  </p>

</div>

Rails and React/Full Stack Application (CI1010)/Rails Backend/app/views/enrolments/_form.html.erb
<%= form_with(model: enrolment) do |form| %>
  <% if enrolment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(enrolment.errors.count, "error") %> prohibited this enrolment from being saved:</h2>

      <ul>
        <% enrolment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.label :student_id, style: "display: block" %>
    <%= form.text_field :student_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Rails and React/Full Stack Application (CI1010)/Rails Backend/app/views/enrolments/edit.html.erb
<h1>Editing enrolment</h1>

<%= render "form", enrolment: @enrolment %>

<br>

<div>
  <%= link_to "Show this enrolment", @enrolment %> |
  <%= link_to "Back to enrolments", enrolments_path %>
</div>

Rails and React/Full Stack Application (CI1010)/Rails Backend/app/views/enrolments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Enrolments</h1>

<div id="enrolments">
  <% @enrolments.each do |enrolment| %>
    <%= render enrolment %>
    <p>
      <%= link_to "Show this enrolment", enrolment %>
    </p>
  <% end %>
</div>

<%= link_to "New enrolment", new_enrolment_path %>

Rails and React/Full Stack Application (CI1010)/Rails Backend/app/views/enrolments/new.html.erb
<h1>New enrolment</h1>

<%= render "form", enrolment: @enrolment %>

<br>

<div>
  <%= link_to "Back to enrolments", enrolments_path %>
</div>

Rails and React/Full Stack Application (CI1010)/Rails Backend/app/views/enrolments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @enrolment %>

<div>
  <%= link_to "Edit this enrolment", edit_enrolment_path(@enrolment) %> |
  <%= link_to "Back to enrolments", enrolments_path %>

  <%= button_to "Destroy this enrolment", @enrolment, method: :delete %>
</div>